### ISSUE TITLE
html -> htm 路由失灵问题

### ISSUE THREAD

**Issue by oott123** [thewakingsands/novice-network#3]
如果 markdown 里写 `(baisc/battle.md#DOT)`，渲染会渲染成 `basic/battle.html#DOT` 而非 `basic/battle.htm#DOT`

需要想办法搞个插件修复，或者给 vuepress 提个 issue

**Comment by chengyuhui** [comment]
正常单击链接的时候应该是没办法遇到这个问题的（是不是router里面修正了？），我个人习惯有些页面会用鼠标中键打开新标签页，所以三天两头触发这个...

这个问题在于 `vuepress-plugin-clean-urls` 似乎仅仅修改了输出路径，却没有修改其他页面的引用路径。其实最快的修改方法是删除该插件，把全站的htm批量替换成html，本地测试了下似乎就没有这个问题了，因为vuepress默认的链接和输出格式应该都是html。

不知道当时使用htm而非html，是不是有什么其他考虑？

**Comment by oott123** [comment]
> 不知道当时使用htm而非html，是不是有什么其他考虑？

因为当时 ml 在游戏里是敏感词。后来 ml 不是敏感词了，但我们不是很确定他们什么时候会加回来。

**Comment by chengyuhui** [comment]
我查看了一些已有的bug，这个扩展名的问题似乎是写死在vuepress的某个地方的（但是我看的代码有点年头了，不知道现在是什么情况），有精力的话我会去看看（反正版本末期了

**Comment by oott123** [comment]
@chengyuhui 好的，因为这个问题不是特别紧要，目前没有人在追踪它，如果你能修好就太棒了！或者找到什么线索也可以和我们同步，非常感激。

**Comment by chengyuhui** [comment]
vuejs/vuepress#2424 我去尝试和VuePress提一下这个问题

我自己实现了下，可以提前对链接进行替换，这样倒是可以避免 `.md` 被换成 `.html` ，但是却破坏了`<router-link>` 的产生。如果需要两全其美的办法，应该需要动核心或者把那部分代码搬过来自己改。

**Comment by chengyuhui** [comment]
如果我的猜测没错的话，404页面其实是有尝试把html重写为htm的（访问一下 https://ff14.org/topic/raid.htm 就可以看到，`pushState`是成功的），但是中间有地方发生了错误，导致不仅不能跳转，整个页面的显示也出现问题。

**Comment by oott123** [comment]
我记得如果链接里不含 hash 的话，转换其实是正确的，只有 .md#xxx 这种才会出事

404 页面出问题的原因我猜是服务端状态（404页面）和客户端状态（渲染正确）不相同导致渲染失败。也许可以通过不预渲染 404 页面得到可以用的 workaround

**Comment by chengyuhui** [comment]
我查看了一下编译出来的js代码，好像对每一个 `.html` 页面都手动指定了对应的 `.htm` 跳转（说实话不是很理解），这个是自己生成的还是第三方插件生成出来的？

**Comment by oott123** [comment]
你说的那些跳转规则都是那个 cleanurl 干的，没有那些规则的话， router 就不会修正链接，那样的话即使你不开新标签他们也是挂的…

**Comment by chengyuhui** [comment]
应该就是SSR的锅，在页面之间跳转无需修改整体结构，但是从404页面直接渲染到正常页面好像是不行的

这也可以解释为啥我在本地测试的好好的，因为本地没有SSR...

**Comment by oott123** [comment]
404 渲染到正常页面不行是因为预渲染的 dom 和 vue 以为的 dom 不一样所以不行，就算 404 的页面结构差不多也不行，和结构有多大差别关系不大。

不过你这么一说我越来越觉得把 404 页面的预渲染取消掉是一个挺好的 workaround ，那么问题就变成了怎么让他不预渲染…
