### ISSUE TITLE
学者的职业介绍中有别字

### ISSUE THREAD

**Issue by AbeliaNymph** [thewakingsands/novice-network#61]
地址[学者|新大陆见闻录](https://ff14.org/job/scholar.htm)

别字在“学者入门”章节的这段话中：

> 需要注意的是，秘术师是 DPS 职业，而学者是治疗职业，在玩家正式成为学者之前，使用副本搜索器时，只能 以 DPS **只能** 参加任务。

其中，“职能”被错写为了“只能”。

**Comment by oott123** [comment]
ty
